#:schema node_modules/wrangler/config-schema.json
name = "next-cf-vibe"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "vibe-db"
database_id = "7198806d-f710-44d2-866e-d5cbcc5a5619"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "vibe-storage"

